ALTER TABLE F DROP FOREIGN KEY FK_F_E_IDE
ALTER TABLE IMMO_JARDIN DROP FOREIGN KEY FK_IMMO_JARDIN_immos_IDIMMO
ALTER TABLE IMMO_JARDIN DROP FOREIGN KEY FK_IMMO_JARDIN_jardins_IDJARDIN
ALTER TABLE B DROP FOREIGN KEY FK_B_A_IDA
ALTER TABLE C DROP FOREIGN KEY FK_C_D_IDD
ALTER TABLE G_H DROP FOREIGN KEY FK_G_H_hs_IDH
ALTER TABLE G_H DROP FOREIGN KEY FK_G_H_G_IDG
DROP TABLE D
DROP TABLE E
DROP TABLE F
DROP TABLE G
DROP TABLE A
DROP TABLE IMMO_JARDIN
DROP TABLE B
DROP TABLE C
DROP TABLE IMMO
DROP TABLE G_H
DROP TABLE H
DROP TABLE JARDIN
DROP TABLE CAR
DROP TABLE RACE
